name = "Poiesis 2"
author = "ATMTeam"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0f2e6a35f174e727f6a26b68e64dfc35bd75ca5a97ffecc544af9f22b28e2d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "datapacks"
