name = "Poiesis 2"
author = "ATMTeam"
version = "2.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc98b5734429fa0358c612b6c9882824b181e6c2dbabff9235f1a8e3ffd38fd8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "datapacks"
