name = "Poiesis Modded"
author = "Converted"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5cae2700a3c1883ab493fe3e4b95c8ad8faa6b15d86e69d1888f49bb9e1d35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
