[[mods]]
filename = "Enchantment Outlines 1.21.1.zip"
name = "Enchantment Outlines 1.21.1"
side = "both"

[mods.download]
hash = "8800f340ea874977b1c882f23a6a9a0a7aebb1b5"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/A32gwfe8/versions/2ldNvURF/Enchantment%20Outlines%201.21.1.zip"
