[[mods]]
filename = "SPEGG BP [1.20-1.x].zip"
name = "SPEGG BP [1.20-1.x]"
side = "both"

[mods.download]
hash = "9b193640ccf3758ce9f0db0644ec025776486670"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/HTcZCflj/versions/TUZMe9HH/SPEGG%20BP%20%5B1.20-1.x%5D.zip"
