"""Immutable semantic digests for the reconciled live Ch1-3 baseline.

The fixture was generated by parsing the live SNBT snapshot in
``evidence/20260907-requested-fixes-baseline``.  Tests compare every quest
compound after canonicalizing SNBT numeric wrappers.  The one documented
exception is Ch3's Patrol Transit rabbit-stew stack split; its total is
compared separately so the original reward identity remains protected.
"""

BASELINE_QUEST_SHA256 = {
    "7A11C0DF00100001": "b7d867ce8341b8a57a898dea15cbc79c70329e5773c09c96a876f4afc077dcb4",
    "7A11C0DF00100003": "cc7cac816cee767fe3c6debdd76227aaa45f024a6119e7e9c21520b9f21c5cd6",
    "7A11C0DF00100005": "982e6726d8ea3bc0ae2bc03d975396a7edfac833bbd235c9cade78ad5cf4a089",
    "7A11C0DF00100006": "e096fd26b8a5f41072ca3e22d54f128a08d79c4f5d3466b619d17c217a0ce974",
    "7A11C0DF00100007": "c259c1d58449e9c4bc90de188fd9bcafbbf43bc16ba211c1ca548d6736fb7f4e",
    "7A11C0DF00200001": "a9e57e073f45658a7566c5bda46df9daf49677fe4b7d950f29a8fed5a4267abd",
    "7A11C0DF00200002": "e4ce82b6b5636658052bcc965a4dd0d8a9c713b1ac9a849a9e02808e0db563f6",
    "7A11C0DF00200003": "2c2584000b95fe145c6b2947a94d0d82e4cee359756b859d678e0687233f4b31",
    "7A11C0DF00200004": "534391f56caa100b6ee4b71e68a046560d11bdf0181a8088549632a825202dc6",
    "7A11C0DF00200007": "ab8d5194368cc9436914dad3a148ff0fd92f3e9236772a4b2b902ac07c0ef3ac",
    "7A11C0DF00300001": "c361a0d394390d0f290652e38440ec24c132c6f964d2fe598077f316f567bb14",
    "7A11C0DF00300002": "f353880c27f3c79fed63ada1430ce4cb04ab8dc6be10f10f9fe97d48fcb25ab5",
    "7A11C0DF00300003": "3360fff14b03a0cde64ba1afd76363a0345df20f2b9201d50037b6a163e54e86",
    "7A11C0DF00300004": "43374344bbeaff4115ccf6c264615bf6c6c3256ed96d014e916c3c66ab37bee7",
    "7A11C0DF00300005": "5daa8e5beb06bdad1c59ecb9a30c41958cadc1c7216f0a24c881336afd1668ae",
    "7A11C0DF00300006": "74c85fae26b0fc1d054dd58fa5797ea90c1216503c18aba7d8d708d15888701c",
    "7A11C0DF00300007": "bd849dd308f80bf9e1853d9c336ea1c6e9f920448d0cd254cce70739ea705388",
    "7A11C0DF00300008": "2ee4db19190fb170384816c708df389701fa8b4436804f8093b55c5d6f7fe772",
    "7A11C0DF00300009": "38f81affbaa3463418a122159d11b3b3d33fbf6e31ea9a5424726f9656ac3ff0",
    "7A11C0DF0030000C": "0a60d3ef5355ecd0ee2d30b0e57a7eb7fcf49e81d9080735cf5b523928da19f7",
    "7A11C0DF0030000D": "3639166f44b5388b96905388b01f4e0fedcf9d5bba2124f97e33122c0229ba0a",
    "7A11C0DF0030000E": "bb2a793ae2cf0607d4d5654e3f830e993d118db17032314b8d19b5829b44cc5c",
    "7A11C0DF0030000F": "328a162443b867763f028a252018014c70b2dbc7fe4f2d4c89ff8deada8a7e45",
    "7A11C0DF00300010": "155e1f2c1152a7fb79642d6258f6bb921b83fe49eade9146c1767557e0932d4d",
    "7A11C0DF00300011": "e527e38ee06341f179bae83c179afc15d2765577bc3d671bd22a1121f8449a43",
}

RABBIT_STEW_SPLIT_QUEST_ID = "7A11C0DF0030000D"
RABBIT_STEW_ORIGINAL_REWARD_ID = "7A11C2DF0030005E"

# The live reconciliation called this ordinary currency reward a
# "construction grant".  The authored wording names the actual Sprocket;
# semantic preservation normalizes only these two explicitly reviewed fields.
SPROCKET_WORDING_QUEST_ID = "7A11C0DF00300002"
SPROCKET_WORDING_REWARD_ID = "7A11C2DF00300006"
BASELINE_SPROCKET_WORDING_DESCRIPTION = (
    "Gather an essential construction stock of stone bricks, logs, iron bars, and lanterns. "
    "Completing this foundation rewards a manageable starter building kit with two stacks of stone, "
    "a stack each of oak and spruce logs, iron, copper, and a sprocket construction grant to redeem at the Market."
)
BASELINE_SPROCKET_WORDING_REWARD_TITLE = "Order Construction Grant"

ARCANE_SPROCKET_WORDING_QUEST_ID = "7A11C0DF0030000E"
ARCANE_SPROCKET_WORDING_REWARD_ID = "7A11C2DF0030004B"
BASELINE_ARCANE_SPROCKET_DESCRIPTION = (
    "Establish the physical study for the Lantern Order's arcane curriculum. Gathering deepslate, dark oak, and amethyst shards unlocks the holy magic branches and awards a compact starter cache of deepslate, dark oak, sand, scaffolding, lapis, an enchanting table, a lectern, and a sprocket construction grant for the Celestial Spire Crate at the Market."
)
