name = "accessories-neoforge-1.1.0-beta.53+1.21.1"
filename = "accessories-neoforge-1.1.0-beta.53+1.21.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "77d75c2e13cfdf56a45cdd29806c1c97c3d250fc"
url = "https://cdn.modrinth.com/data/jtmvUHXj/versions/Fb55Fgjz/accessories-neoforge-1.1.0-beta.53%2B1.21.1.jar"
