name = "animal_feeding_trough-1.1.2+1.21-neoforge"
filename = "animal_feeding_trough-1.1.2+1.21-neoforge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "6c29bbeab4b2c174d9f66d6a3e9ef4e136705c5b"
url = "https://cdn.modrinth.com/data/bRFWnJ87/versions/9u4bmtUp/animal_feeding_trough-1.1.2%2B1.21-neoforge.jar"
