[[mods]]
filename = "architectury-13.0.8-neoforge.jar"
name = "architectury-13.0.8-neoforge"
side = "both"

[mods.download]
hash = "6ca11d3cc136bf69bb8f4d56982481eb85b5100b"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/lhGA9TYQ/versions/ZxYGwlk0/architectury-13.0.8-neoforge.jar"
