[[mods]]
filename = "azurelib-neo-1.21.1-3.1.4.jar"
name = "azurelib-neo-1.21.1-3.1.4"
side = "both"

[mods.download]
hash = "91bb30a4458a968fb683576d2972cda02bcd30f5"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/7zlUOZvb/versions/uatMybJK/azurelib-neo-1.21.1-3.1.4.jar"
