name = "BetterEnd-21.0.24"
filename = "BetterEnd-21.0.24.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "a4344efa302c04ab11fa5313032836c662fb540c"
url = "https://cdn.modrinth.com/data/IcERKldh/versions/QWW9Gwwf/BetterEnd-21.0.24.jar"
