[[mods]]
filename = "BetterF3-11.0.3-NeoForge-1.21.1.jar"
name = "BetterF3-11.0.3-NeoForge-1.21.1"
side = "both"

[mods.download]
hash = "8fa17df26d3650416bc124be7a264bc1566a3b26"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/8shC1gFX/versions/maXNB1dn/BetterF3-11.0.3-NeoForge-1.21.1.jar"
