name = "cobblenav-neoforge-2.3.2"
filename = "cobblenav-neoforge-2.3.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "f284be7129231ce4e36cdb0fa576475f9155cf63"
url = "https://cdn.modrinth.com/data/bI8Nt3uA/versions/OMsYBNWp/cobblenav-neoforge-2.3.2.jar"
