name = "continuity-3.0.0+1.21.neoforge"
filename = "continuity-3.0.0+1.21.neoforge.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "0aecd2d043ac25299254623fafdd9129ab2ba9c2"
url = "https://cdn.modrinth.com/data/1IjD5062/versions/eXGUs5sy/continuity-3.0.0%2B1.21.neoforge.jar"
