[[mods]]
filename = "create-1.21.1-6.0.9.jar"
name = "create-1.21.1-6.0.9"
side = "both"

[mods.download]
hash = "bf08bf8980c080f42d6f644f4f44a725cf7c3be9"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/LNytGWDc/versions/n7NADxiG/create-1.21.1-6.0.9.jar"
