[[mods]]
filename = "CreateNumismatics-1.0.19+neoforge-mc1.21.1.jar"
name = "CreateNumismatics-1.0.19+neoforge-mc1.21.1"
side = "both"

[mods.download]
hash = "cfc4b7dd2b715658b513671df871a394ee67cd01"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/Jdbbtt0i/versions/KMFhYqZ9/CreateNumismatics-1.0.19%2Bneoforge-mc1.21.1.jar"
