[[mods]]
filename = "curios-neoforge-9.5.1+1.21.1.jar"
name = "curios-neoforge-9.5.1+1.21.1"
side = "both"

[mods.download]
hash = "418fcd42e3a7844c9bdc71c9b6401fdb3894e0c4"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/vvuO3ImH/versions/yohfFbgD/curios-neoforge-9.5.1%2B1.21.1.jar"
