name = "dye_depot-2.0.2-neoforge"
filename = "dye_depot-2.0.2-neoforge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "6157db3c60737cdf1b5d74e047c36c97d3ee81fc"
url = "https://cdn.modrinth.com/data/dl88rsIq/versions/LcGfPPua/dye_depot-2.0.2-neoforge.jar"
