name = "dye_the_world-2.1.1"
filename = "dye_the_world-2.1.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1e09d4baf92e6fe188129e3030b3a1fdd7d61a7b"
url = "https://cdn.modrinth.com/data/naUMeOvG/versions/8hFupvAV/dye_the_world-2.1.1.jar"
