[[mods]]
filename = "envelope-neoforge-1.21.1-0.5.2.jar"
name = "envelope-neoforge-1.21.1-0.5.2"
side = "both"

[mods.download]
hash = "e4b90b114bba475d39185a1d14cbc553e15b66a3"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/bINSbhYK/versions/1X04oyJ2/envelope-neoforge-1.21.1-0.5.2.jar"
