[[mods]]
filename = "hauntedharvest-1.21-3.3.9-neoforge.jar"
name = "hauntedharvest-1.21-3.3.9-neoforge"
side = "both"

[mods.download]
hash = "f7853293553668f4c5a924f112f2669d89e21313"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/a378ICDH/versions/W3GQrLju/hauntedharvest-1.21-3.3.9-neoforge.jar"
