[[mods]]
filename = "hologenica-1.0.2-neoforge-1.21.1.jar"
name = "hologenica-1.0.2-neoforge-1.21.1"
side = "both"

[mods.download]
hash = "f4ef977f11ffd1d2c534644eb7c3ed0a15a69d31"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/huOhn9zP/versions/ZcZ8jcmi/hologenica-1.0.2-neoforge-1.21.1.jar"
