[[mods]]
filename = "ImmediatelyFast-NeoForge-1.6.10+1.21.1.jar"
name = "ImmediatelyFast-NeoForge-1.6.10+1.21.1"
side = "both"

[mods.download]
hash = "f1f5cccd7cb59d875f44566b2e557ccecc8c33fb"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/5ZwdcRci/versions/PhxY0iHw/ImmediatelyFast-NeoForge-1.6.10%2B1.21.1.jar"
