[[mods]]
filename = "ImmersiveUI-NEOFORGE-0.3.3+1.21.1.jar"
name = "ImmersiveUI-NEOFORGE-0.3.3+1.21.1"
side = "both"

[mods.download]
hash = "5e9dda03c6142400b95dc3114675e07c943d554d"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/9wv7LuMc/versions/wtmSnIFo/ImmersiveUI-NEOFORGE-0.3.3%2B1.21.1.jar"
