[[mods]]
filename = "iris-neoforge-1.8.12+mc1.21.1.jar"
name = "iris-neoforge-1.8.12+mc1.21.1"
side = "both"

[mods.download]
hash = "a3e6355915c7d3b2bc392724795113e51d289378"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/t3ruzodq/iris-neoforge-1.8.12%2Bmc1.21.1.jar"
