[[mods]]
filename = "kotlinforforge-5.11.0-all.jar"
name = "kotlinforforge-5.11.0-all"
side = "both"

[mods.download]
hash = "4d83e8a8e8cb06b306d2cea1e903680fe513f1f3"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/ordsPcFz/versions/NrSebcsG/kotlinforforge-5.11.0-all.jar"
