[[mods]]
filename = "LeaveMyBarsAlone-v21.1.2-1.21.1-NeoForge.jar"
name = "LeaveMyBarsAlone-v21.1.2-1.21.1-NeoForge"
side = "both"

[mods.download]
hash = "7156b542431ea057539070c0c00feb8c9f58c099"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/gK9mebQg/versions/27kYf7JI/LeaveMyBarsAlone-v21.1.2-1.21.1-NeoForge.jar"
