[[mods]]
filename = "letsdo-vinery-neoforge-1.5.3.jar"
name = "letsdo-vinery-neoforge-1.5.3"
side = "both"

[mods.download]
hash = "e920dbb720c2c010c45b137d195a5cc72a9afdd2"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/1DWmBJVA/versions/ZywXpLC6/letsdo-vinery-neoforge-1.5.3.jar"
