[[mods]]
filename = "letsdo-farm_and_charm-neoforge-1.1.21.jar"
name = "letsdo-farm_and_charm-neoforge-1.1.21"
side = "both"

[mods.download]
hash = "a8f001fad9be0ce86cff97d6fc3bb4af652abba9"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/HJetCzWo/versions/muipCbfC/letsdo-farm_and_charm-neoforge-1.1.21.jar"
