[[mods]]
filename = "libjf-3.17.6+forge.jar"
name = "libjf-3.17.6+forge"
side = "both"

[mods.download]
hash = "b6c4ffb3260f495344fa56ef3489c01e2b9552de"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/WKwQAwke/versions/U2XgYJpS/libjf-3.17.6%2Bforge.jar"
