name = "mcpitanlib-3.5.1-1.21.1-neoforge"
filename = "mcpitanlib-3.5.1-1.21.1-neoforge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "e1003c21b0a64f65f17183c114f2e3ae74c7dd11"
url = "https://cdn.modrinth.com/data/uNRoUnGT/versions/w0WsZ5yx/mcpitanlib-3.5.1-1.21.1-neoforge.jar"
