name = "open-parties-and-claims-neoforge-1.21.1-0.25.10"
filename = "open-parties-and-claims-neoforge-1.21.1-0.25.10.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "bbd78fbeb076473bc19b247491490c4ac0139dd3"
url = "https://cdn.modrinth.com/data/gF3BGWvG/versions/g5OOSal5/open-parties-and-claims-neoforge-1.21.1-0.25.10.jar"
