[[mods]]
filename = "particular-1.21.1-NeoForge-1.1.7.jar"
name = "particular-1.21.1-NeoForge-1.1.7"
side = "both"

[mods.download]
hash = "39d2fa3c396bf75a00078922dd6c2a7bf9f63f46"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/pYFUU6cq/versions/QmW99EbW/particular-1.21.1-NeoForge-1.1.7.jar"
