[[mods]]
filename = "polymorph-neoforge-1.1.0+1.21.1.jar"
name = "polymorph-neoforge-1.1.0+1.21.1"
side = "both"

[mods.download]
hash = "84f8c539fa326dc723ae62b7a6916d6b01982d07"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/tagwiZkJ/versions/VEburL70/polymorph-neoforge-1.1.0%2B1.21.1.jar"
