[[mods]]
filename = "PuzzlesLib-v21.1.39-1.21.1-NeoForge.jar"
name = "PuzzlesLib-v21.1.39-1.21.1-NeoForge"
side = "both"

[mods.download]
hash = "bcc0900fbbf6d6fc5ca05039cd5725e6145225f2"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/QAGBst4M/versions/EgWWSAhJ/PuzzlesLib-v21.1.39-1.21.1-NeoForge.jar"
