[[mods]]
filename = "Quark-4.1-475.jar"
name = "Quark-4.1-475"
side = "both"

[mods.download]
hash = "ad9f7c9ab935f70d431ceea35976a52f9bcd26e9"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/qnQsVE2z/versions/IvW220rK/Quark-4.1-475.jar"
