[[mods]]
filename = "SereneSeasons-neoforge-1.21.1-10.1.0.3.jar"
name = "SereneSeasons-neoforge-1.21.1-10.1.0.3"
side = "both"

[mods.download]
hash = "127e4a3e699dafebc512e1fa7983f245b49cb420"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/e0bNACJD/versions/SPj5bJoM/SereneSeasons-neoforge-1.21.1-10.1.0.3.jar"
