[[mods]]
filename = "smoothgui-neoforge-1.21.1-1.1.0.jar"
name = "smoothgui-neoforge-1.21.1-1.1.0"
side = "both"

[mods.download]
hash = "7f92bfc79f754b68855770610ad79a3934703c25"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/j6yrZogB/versions/WVSpzVhZ/smoothgui-neoforge-1.21.1-1.1.0.jar"
