name = "sodiumoptionsapi-neoforge-1.0.10-1.21.1"
filename = "sodiumoptionsapi-neoforge-1.0.10-1.21.1.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "5d014d031fa77ab600e07835b032ef4dcb79b442"
url = "https://cdn.modrinth.com/data/Es5v4eyq/versions/lrsX3TMS/sodiumoptionsapi-neoforge-1.0.10-1.21.1.jar"
