[[mods]]
filename = "sodiumdynamiclights-neoforge-1.0.10-1.21.1.jar"
name = "sodiumdynamiclights-neoforge-1.0.10-1.21.1"
side = "both"

[mods.download]
hash = "02e9bc7ba28147cdf2d608ecf4f2c1eab34b4652"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/PxQSWIcD/versions/XI0WLXdn/sodiumdynamiclights-neoforge-1.0.10-1.21.1.jar"
