[[mods]]
filename = "transmog-neoforge-1.6.0+1.21.1.jar"
name = "transmog-neoforge-1.6.0+1.21.1"
side = "both"

[mods.download]
hash = "fb37ae0a35e8bb9340e61007275121f02cf7a8bc"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/Th33t82F/versions/E3JkRJnV/transmog-neoforge-1.6.0%2B1.21.1.jar"
