[[mods]]
filename = "VampiresNeedUmbrellas-1.21.1-1.0.3.jar"
name = "VampiresNeedUmbrellas-1.21.1-1.0.3"
side = "both"

[mods.download]
hash = "80b0bde4bb57fc3109585232df348e1820277d1b"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/FaUysFni/versions/gA6GeHzf/VampiresNeedUmbrellas-1.21.1-1.0.3.jar"
