[[mods]]
filename = "VampiresDelight-1.21.1-0.1.11b.jar"
name = "VampiresDelight-1.21.1-0.1.11b"
side = "both"

[mods.download]
hash = "e032d75a9ebd1ffc543dac16f204b4fb4fd9e972"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/9Vo2deFq/versions/HX3GVV8o/VampiresDelight-1.21.1-0.1.11b.jar"
