[[mods]]
filename = "xaerominimap-neoforge-1.21.1-25.3.10.jar"
name = "xaerominimap-neoforge-1.21.1-25.3.10"
side = "both"

[mods.download]
hash = "d4828332dd831455429156b6cfa24aa9bd99dd77"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/1bokaNcj/versions/CatMvRfN/xaerominimap-neoforge-1.21.1-25.3.10.jar"
