[[mods]]
filename = "YungsApi-1.21.1-NeoForge-5.1.6.jar"
name = "YungsApi-1.21.1-NeoForge-5.1.6"
side = "both"

[mods.download]
hash = "e1c394779fb9e038e4f7a1b4558d0432607d263b"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/Ua7DFN59/versions/ZB22DE9q/YungsApi-1.21.1-NeoForge-5.1.6.jar"
