[[mods]]
filename = "Zeta-1.1-39.jar"
name = "Zeta-1.1-39"
side = "both"

[mods.download]
hash = "ef6f2e1a625a9f8770a33576b682a228e441747a"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/MVARlG2f/versions/iyNxYFme/Zeta-1.1-39.jar"
