name = "Zeta-1.1-39"
filename = "Zeta-1.1-39.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ef6f2e1a625a9f8770a33576b682a228e441747a"
url = "https://cdn.modrinth.com/data/MVARlG2f/versions/iyNxYFme/Zeta-1.1-39.jar"
