[[mods]]
filename = "zipline-neoforge-1.21.1-1.0.3.jar"
name = "zipline-neoforge-1.21.1-1.0.3"
side = "both"

[mods.download]
hash = "6571acc7fc3abf4a16f85a8b37d1ff16751d97e7"
hash-format = "sha1"
url = "https://cdn.modrinth.com/data/C1MoWQlb/versions/EezeLHnd/zipline-neoforge-1.21.1-1.0.3.jar"
